#pragma once
#include <windows.h>

enum CustomGamepadInputID : UINT {
    GAMEPAD_ID_A = 0,
    GAMEPAD_ID_B,
    GAMEPAD_ID_X,
    GAMEPAD_ID_Y,

    GAMEPAD_ID_DPAD_UP,
    GAMEPAD_ID_DPAD_DOWN,
    GAMEPAD_ID_DPAD_LEFT,
    GAMEPAD_ID_DPAD_RIGHT,

    GAMEPAD_ID_START,
    GAMEPAD_ID_BACK,

    GAMEPAD_ID_GUIDE,
    GAMEPAD_ID_MISC1,
    GAMEPAD_ID_PADDLE1,
    GAMEPAD_ID_PADDLE2,
    GAMEPAD_ID_PADDLE3,
    GAMEPAD_ID_PADDLE4,

    GAMEPAD_ID_TOUCHPAD_BUTTON,

    GAMEPAD_ID_LSB,
    GAMEPAD_ID_RSB,

    GAMEPAD_ID_LB,
    GAMEPAD_ID_RB,

    GAMEPAD_ID_LT,
    GAMEPAD_ID_RT,

    GAMEPAD_ID_LSU,
    GAMEPAD_ID_LSD,
    GAMEPAD_ID_LSL,
    GAMEPAD_ID_LSR,

    GAMEPAD_ID_RSU,
    GAMEPAD_ID_RSD,
    GAMEPAD_ID_RSL,
    GAMEPAD_ID_RSR,

    GAMEPAD_ID_LS_INNER,
    GAMEPAD_ID_LS_OUTER,
    GAMEPAD_ID_RS_INNER,
    GAMEPAD_ID_RS_OUTER,

    GAMEPAD_ID_COUNT
};