; ===================================================================
; Configuration File for GtoMnK (Gamepad to Mouse and Keyboard)
; ===================================================================
; Check for more details: https://github.com/SAM1430B/GtoMnK/wiki

[Info]
Name=
Ver=1.4.0

[API]
InputMethod=2

[Hooks]
GetCursorposHook=1
SetCursorposHook=1
ClipCursorHook=1

GetKeystateHook=1
GetAsyncKeystateHook=1
GetKeyboardstateHook=1

[MessageFilter]
RawInputFilter=0
MouseMoveFilter=0
MouseActivateFilter=0
WindowActivateFilter=0
WindowActivateAppFilter=0
MouseWheelFilter=0
MouseButtonFilter=0
KeyboardButtonFilter=0

[Settings]
Controllerid=0
DrawProtoFakeCursor=0
StartUpDelay=0

[StickToMouse]
ThumbstickToMouse=2

Sensitivity=2.60
Horizontal_Sensitivity=0.00
Vertical_Sensitivity=0.00

Radial_Deadzone=0.10

[KeyMapping]
EnableMouseDoubleClick=0
StickAsButtonDeadzone=0.25
TriggerThreshold=40

A = 13
B = 0
X = 0
Y = 0

; Preset for Arrow Keys
D_UP = 14
D_DOWN = 15
D_LEFT = 16
D_RIGHT = 17

RB = 0
LB = 0
RSB = 0
LSB = 4

; Preset for mouse buttons
RT = -1
LT = -2

; Preset for WASD
LSU = 47
LSD = 43
LSL = 25
LSR = 28

RSU = 0
RSD = 0
RSL = 0
RSR = 0

; Preset for Escape and TAB
Start = 1
Back = 3