# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        platform: [x64, x86]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Inject Build Properties
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $props = @"
        <Project>
          <ItemDefinitionGroup>
            <Link>
              <AdditionalLibraryDirectories>`$(MSBuildThisFileDirectory)include\EasyHook\Build\x86\netfx3.5-Release;`$(MSBuildThisFileDirectory)include\EasyHook\Build\x64\netfx3.5-Release;`$(MSBuildThisFileDirectory)include\EasyHook\Build\x86\netfx4-Release;`$(MSBuildThisFileDirectory)include\EasyHook\Build\x64\netfx4-Release;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
            </Link>
            <ClCompile>
              <AdditionalIncludeDirectories>`$(VC_ATLMFC_IncludePath);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
            </ClCompile>
          </ItemDefinitionGroup>
        </Project>
        "@
        Set-Content -Path "Directory.Build.props" -Value $props

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
        $devenv = & $vswhere -latest -find Common7\IDE\devenv.com
        & $devenv GtoMnK.sln /Upgrade
        & $devenv GtoMnK.sln /Build "${{env.BUILD_CONFIGURATION}}|${{matrix.platform}}"
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
